=== jake-lewis/workspace-configuration-tool/src/main/resources/example config/workspaceConfigSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="https://github.com/jsjlewis96/project" targetNamespace="https://github.com/jsjlewis96/project">
    <xs:element name="structure" type="structureType"/>
    <xs:complexType name="structureType">
        <xs:sequence>
            <xs:element type="configType" name="config"/>
            <xs:element type="dirsType" name="dirs"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="dirsType">
        <xs:sequence>
            <xs:element type="dirType" name="dir" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="configType">
        <xs:sequence>
            <xs:element type="xs:string" name="project"/>
            <xs:element type="xs:string" name="root"/>
            <xs:element type="xs:string" name="target"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="dirType">
        <xs:sequence>
            <xs:element name="prefix" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:string" name="separator" minOccurs="0"/>
            <xs:element name="name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="dirsType" name="dirs" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== jake-lewis/workspace-configuration-tool/src/main/resources/example config/exampleConfig.xml
<?xml version="1.0" encoding="utf-8"?>

<structure xmlns="https://github.com/jsjlewis96/project"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://github.com/jsjlewis96/project workspaceConfigSchema.xsd">
    <config>
        <project>testProject</project>
        <root>rootPath</root>
        <target>targetPath</target>
    </config>
    <dirs>
        <dir>
            <name>Management</name>
            <dirs>
                <dir>
                    <prefix>MS</prefix>
                    <separator>.</separator>
                    <name>Project Schedule</name>
                    <dirs>
                        <dir>
                            <prefix>1</prefix>
                            <name>Gantt Chart</name>
                        </dir>
                        <dir>
                            <prefix>2</prefix>
                            <name>Process Matrix</name>
                        </dir>
                    </dirs>
                </dir>
            </dirs>
        </dir>
    </dirs>
</structure>

=== jake-lewis/workspace-configuration-tool/target/classes/example config/exampleConfig.xml
<?xml version="1.0" encoding="utf-8"?>

<structure xmlns="https://github.com/jsjlewis96/project"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://github.com/jsjlewis96/project workspaceConfigSchema.xsd">
    <config>
        <project>testProject</project>
        <root>rootPath</root>
        <target>targetPath</target>
    </config>
    <dirsRoot>
        <dir>
            <name>Management</name>
            <dirs>
                <dir>
                    <prefix>MS</prefix>
                    <separator>.</separator>
                    <name>Project Schedule</name>
                    <dirs>
                        <dir>
                            <prefix>1</prefix>
                            <name>Gantt Chart</name>
                        </dir>
                        <dir>
                            <prefix>2</prefix>
                            <name>Process Matrix</name>
                        </dir>
                    </dirs>
                </dir>
            </dirs>
        </dir>
        <dir>
            <name>Tech</name>
            <dirs>
                <dir>
                    <prefix>TQ</prefix>
                    <separator>.</separator>
                    <name>Peer Review</name>
                    <dirs>
                        <dir>
                            <prefix>1</prefix>
                            <name>Code Review</name>
                        </dir>
                        <dir>
                            <prefix>2</prefix>
                            <name>Design Review</name>
                        </dir>
                    </dirs>
                </dir>
                <dir>
                    <prefix>TS</prefix>
                    <separator>.</separator>
                    <name>System Design Spec</name>
                    <dirs>
                        <dir>
                            <prefix>1</prefix>
                            <separator>-</separator>
                            <name>System and Subsystem Design Description</name>
                            <dirs>
                                <dir>
                                    <prefix>01</prefix>
                                    <name>File Structure Project SSDD</name>
                                </dir>
                                <dir>
                                    <prefix>02</prefix>
                                    <name>OTHER PROJECT SSDD</name>
                                </dir>
                            </dirs>
                        </dir>
                        <dir>
                            <prefix>2</prefix>
                            <name>OTHER DESIGN SPEC DOCS</name>
                        </dir>
                    </dirs>
                </dir>
            </dirs>
        </dir>
    </dirsRoot>
</structure>
